# Generated by Django 6.0.7 on 2026-09-07 12:15

import django.db.models.deletion
import pretalx_arc_application.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mail', '0016_replace_notifications_placeholder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualMail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=998)),
                ('recipients', models.JSONField(default=list)),
                ('cc', models.JSONField(default=list)),
                ('bcc', models.JSONField(default=list)),
                ('sender', models.TextField()),
                ('body', models.TextField()),
                ('message', models.FileField(max_length=255, storage=pretalx_arc_application.storage.PrivateUploadStorage(directory_permissions_mode=448, file_permissions_mode=384), upload_to='manual-mail/')),
                ('requires_validation', models.BooleanField(default=False)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('handed_over_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.queuedmail')),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
    ]
