# Generated by Django 6.0.7 on 2026-09-08 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0044_event_locales_json'),
        ('mail', '0016_replace_notifications_placeholder'),
        ('pretalx_arc_application', '0001_initial'),
        ('submission', '0108_alter_resource_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(model_name='manualmail', name='subject_users', field=models.ManyToManyField(blank=True, related_name='recruitment_manual_mails', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='manualmail', name='subject_submissions', field=models.ManyToManyField(blank=True, related_name='recruitment_manual_mails', to='submission.submission')),
        migrations.CreateModel(
            name='PendingFileErasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='MailSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_subjects', to='mail.queuedmail')),
                ('submissions', models.ManyToManyField(to='submission.submission')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('lawful_basis', models.TextField()),
                ('retention_days', models.PositiveIntegerField(null=True)),
                ('hosting_policy', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_policy', to='event.event')),
            ],
        ),
    ]
